name: "Terraform Plan"

# Trigger when a pull request is received
on:
  pull_request:
    branches: [ develop ]

env:
  DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Static analysis of Terraform templates to spot potential security issues
      # Marketplace: https://github.com/marketplace/actions/terraform-security-scan
      - name: "Setup - Security Scan"
        uses: triat/terraform-security-scan@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.0.1

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Init"
        run: terraform init -input=false

      # Init pulls credentials from the .aws/credentials file by default
      - name: "Run - Terraform Workspace"
        run: terraform workspace new develop

      # Genrate terraform plan and store the artifact
      - name: "Run - Terraform Plan"
        id: plan
        run: terraform plan -input=false -no-color -out=./plans/tf_develop_plan
      - uses: actions/upload-artifact@v2
        with:
          name: generated-plan
          path: ./plans/tf_develop_plan

  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
 
    environment: 
      name: develop

    # Add CI workflow dependency
    needs: [terraform-plan]

    steps:
      # Checkout the code
      # Marketplace: https://github.com/marketplace/actions/checkout
      - name: "Setup - Checkout"
        uses: actions/checkout@v2.1.0

      # Genrate download the terraform plan stored in the artifact
      - uses: actions/download-artifact@v2
        with:
          name: generated-plan

      # Downloads a specific version of Terraform CLI and adds it to PATH
      # Marketplace: https://github.com/marketplace/actions/hashicorp-setup-terraform
      - name: "Setup - Terraform CLI"
        uses: hashicorp/setup-terraform@v1.0.1

      - name: "Run - Terraform Init"
        run: terraform init -input=false

      # Auto-approve prevents the requirement of human interaction
      - name: "Run - Terraform Apply"
        run: terraform apply "./plans/tf_develop_plan" -auto-approve